/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef JBODDEVTEMPERATURETABLE_INTERFACE_H
#define JBODDEVTEMPERATURETABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "jbodDevTemperatureTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _jbodDevTemperatureTable_initialize_interface(jbodDevTemperatureTable_registration * user_ctx,
                                    u_long flags);
void _jbodDevTemperatureTable_shutdown_interface(jbodDevTemperatureTable_registration * user_ctx);

jbodDevTemperatureTable_registration *
jbodDevTemperatureTable_registration_get( void );

jbodDevTemperatureTable_registration *
jbodDevTemperatureTable_registration_set( jbodDevTemperatureTable_registration * newreg );

netsnmp_container *jbodDevTemperatureTable_container_get( void );
int jbodDevTemperatureTable_container_size( void );

    jbodDevTemperatureTable_rowreq_ctx * jbodDevTemperatureTable_allocate_rowreq_ctx(void *);
void jbodDevTemperatureTable_release_rowreq_ctx(jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx);

int jbodDevTemperatureTable_index_to_oid(netsnmp_index *oid_idx,
                            jbodDevTemperatureTable_mib_index *mib_idx);
int jbodDevTemperatureTable_index_from_oid(netsnmp_index *oid_idx,
                              jbodDevTemperatureTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void jbodDevTemperatureTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* JBODDEVTEMPERATURETABLE_INTERFACE_H */
/** @} */
