/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef JBODDEVDISKTABLE_DATA_ACCESS_H
#define JBODDEVDISKTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevDiskTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevDiskTable is subid 5 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.5, length: 10
*/


    int jbodDevDiskTable_init_data(jbodDevDiskTable_registration * jbodDevDiskTable_reg);


void jbodDevDiskTable_container_init(netsnmp_container **container_ptr_ptr);
void jbodDevDiskTable_container_shutdown(netsnmp_container *container_ptr);

int jbodDevDiskTable_container_load(netsnmp_container *container);
void jbodDevDiskTable_container_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int jbodDevDiskTable_row_prep( jbodDevDiskTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* JBODDEVDISKTABLE_DATA_ACCESS_H */
