/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
#ifndef JBODDEVTEMPERATURETABLE_H
#define JBODDEVTEMPERATURETABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(INWIN-JBOD-MIB)
config_require(INWIN-JBOD-MIB/jbodDevTemperatureTable/jbodDevTemperatureTable_interface)
config_require(INWIN-JBOD-MIB/jbodDevTemperatureTable/jbodDevTemperatureTable_data_access)
config_require(INWIN-JBOD-MIB/jbodDevTemperatureTable/jbodDevTemperatureTable_data_get)
config_require(INWIN-JBOD-MIB/jbodDevTemperatureTable/jbodDevTemperatureTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for jbodDevTemperatureTable */
#include "jbodDevTemperatureTable_oids.h"

/* enum definions */
#include "jbodDevTemperatureTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_jbodDevTemperatureTable(void);
void shutdown_jbodDevTemperatureTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevTemperatureTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevTemperatureTable is subid 2 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.2, length: 10
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review jbodDevTemperatureTable registration context.
     */
typedef netsnmp_data_list jbodDevTemperatureTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review jbodDevTemperatureTable data context structure.
 * This structure is used to represent the data for jbodDevTemperatureTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * jbodDevTemperatureTable.
 */
typedef struct jbodDevTemperatureTable_data_s {
    
        /*
         * temperatureDescription(2)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   temperatureDescription[128];
size_t      temperatureDescription_len; /* # of char elements, not bytes */
    
        /*
         * temperatureStatus(3)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   temperatureStatus[128];
size_t      temperatureStatus_len; /* # of char elements, not bytes */
    
        /*
         * temperatureValue(4)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   temperatureValue;
    
        /*
         * temperatureUnit(5)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   temperatureUnit[128];
size_t      temperatureUnit_len; /* # of char elements, not bytes */
    
} jbodDevTemperatureTable_data;


/*
 * TODO:120:r: |-> Review jbodDevTemperatureTable mib index.
 * This structure is used to represent the index for jbodDevTemperatureTable.
 */
typedef struct jbodDevTemperatureTable_mib_index_s {

        /*
         * temperatureIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/R/d/h
         */
   long   temperatureIndex;


} jbodDevTemperatureTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review jbodDevTemperatureTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_jbodDevTemperatureTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review jbodDevTemperatureTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * jbodDevTemperatureTable_rowreq_ctx pointer.
 */
typedef struct jbodDevTemperatureTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_jbodDevTemperatureTable_IDX_LEN];
    
    jbodDevTemperatureTable_mib_index        tbl_idx;
    
    jbodDevTemperatureTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to jbodDevTemperatureTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *jbodDevTemperatureTable_data_list;

} jbodDevTemperatureTable_rowreq_ctx;

typedef struct jbodDevTemperatureTable_ref_rowreq_ctx_s {
    jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx;
} jbodDevTemperatureTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int jbodDevTemperatureTable_pre_request(jbodDevTemperatureTable_registration * user_context);
    int jbodDevTemperatureTable_post_request(jbodDevTemperatureTable_registration * user_context,
        int rc);

    int jbodDevTemperatureTable_rowreq_ctx_init(jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void jbodDevTemperatureTable_rowreq_ctx_cleanup(jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx);


    jbodDevTemperatureTable_rowreq_ctx *
                  jbodDevTemperatureTable_row_find_by_mib_index(jbodDevTemperatureTable_mib_index *mib_idx);

extern const oid jbodDevTemperatureTable_oid[];
extern const int jbodDevTemperatureTable_oid_size;


#include "jbodDevTemperatureTable_interface.h"
#include "jbodDevTemperatureTable_data_access.h"
#include "jbodDevTemperatureTable_data_get.h"
#include "jbodDevTemperatureTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* JBODDEVTEMPERATURETABLE_H */
/** @} */
