/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef JBODDEVLOGTABLE_INTERFACE_H
#define JBODDEVLOGTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "jbodDevLogTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _jbodDevLogTable_initialize_interface(jbodDevLogTable_registration * user_ctx,
                                    u_long flags);
void _jbodDevLogTable_shutdown_interface(jbodDevLogTable_registration * user_ctx);

jbodDevLogTable_registration *
jbodDevLogTable_registration_get( void );

jbodDevLogTable_registration *
jbodDevLogTable_registration_set( jbodDevLogTable_registration * newreg );

netsnmp_container *jbodDevLogTable_container_get( void );
int jbodDevLogTable_container_size( void );

    jbodDevLogTable_rowreq_ctx * jbodDevLogTable_allocate_rowreq_ctx(void *);
void jbodDevLogTable_release_rowreq_ctx(jbodDevLogTable_rowreq_ctx *rowreq_ctx);

int jbodDevLogTable_index_to_oid(netsnmp_index *oid_idx,
                            jbodDevLogTable_mib_index *mib_idx);
int jbodDevLogTable_index_from_oid(netsnmp_index *oid_idx,
                              jbodDevLogTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void jbodDevLogTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* JBODDEVLOGTABLE_INTERFACE_H */
/** @} */
