/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef JBODDEVDISKTABLE_INTERFACE_H
#define JBODDEVDISKTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "jbodDevDiskTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _jbodDevDiskTable_initialize_interface(jbodDevDiskTable_registration * user_ctx,
                                    u_long flags);
void _jbodDevDiskTable_shutdown_interface(jbodDevDiskTable_registration * user_ctx);

jbodDevDiskTable_registration *
jbodDevDiskTable_registration_get( void );

jbodDevDiskTable_registration *
jbodDevDiskTable_registration_set( jbodDevDiskTable_registration * newreg );

netsnmp_container *jbodDevDiskTable_container_get( void );
int jbodDevDiskTable_container_size( void );

    jbodDevDiskTable_rowreq_ctx * jbodDevDiskTable_allocate_rowreq_ctx(void *);
void jbodDevDiskTable_release_rowreq_ctx(jbodDevDiskTable_rowreq_ctx *rowreq_ctx);

int jbodDevDiskTable_index_to_oid(netsnmp_index *oid_idx,
                            jbodDevDiskTable_mib_index *mib_idx);
int jbodDevDiskTable_index_from_oid(netsnmp_index *oid_idx,
                              jbodDevDiskTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void jbodDevDiskTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* JBODDEVDISKTABLE_INTERFACE_H */
/** @} */
