/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef JBODDEVLOGTABLE_DATA_ACCESS_H
#define JBODDEVLOGTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevLogTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevLogTable is subid 6 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.6, length: 10
*/


    int jbodDevLogTable_init_data(jbodDevLogTable_registration * jbodDevLogTable_reg);


void jbodDevLogTable_container_init(netsnmp_container **container_ptr_ptr);
void jbodDevLogTable_container_shutdown(netsnmp_container *container_ptr);

int jbodDevLogTable_container_load(netsnmp_container *container);
void jbodDevLogTable_container_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int jbodDevLogTable_row_prep( jbodDevLogTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* JBODDEVLOGTABLE_DATA_ACCESS_H */
