/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef JBODDEVVOLTAGETABLE_INTERFACE_H
#define JBODDEVVOLTAGETABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "jbodDevVoltageTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _jbodDevVoltageTable_initialize_interface(jbodDevVoltageTable_registration * user_ctx,
                                    u_long flags);
void _jbodDevVoltageTable_shutdown_interface(jbodDevVoltageTable_registration * user_ctx);

jbodDevVoltageTable_registration *
jbodDevVoltageTable_registration_get( void );

jbodDevVoltageTable_registration *
jbodDevVoltageTable_registration_set( jbodDevVoltageTable_registration * newreg );

netsnmp_container *jbodDevVoltageTable_container_get( void );
int jbodDevVoltageTable_container_size( void );

    jbodDevVoltageTable_rowreq_ctx * jbodDevVoltageTable_allocate_rowreq_ctx(void *);
void jbodDevVoltageTable_release_rowreq_ctx(jbodDevVoltageTable_rowreq_ctx *rowreq_ctx);

int jbodDevVoltageTable_index_to_oid(netsnmp_index *oid_idx,
                            jbodDevVoltageTable_mib_index *mib_idx);
int jbodDevVoltageTable_index_from_oid(netsnmp_index *oid_idx,
                              jbodDevVoltageTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void jbodDevVoltageTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* JBODDEVVOLTAGETABLE_INTERFACE_H */
/** @} */
