/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 *
 * @file jbodDevTemperatureTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef JBODDEVTEMPERATURETABLE_DATA_GET_H
#define JBODDEVTEMPERATURETABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevTemperatureTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevTemperatureTable is subid 2 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.2, length: 10
*/
    /*
     * indexes
     */

    int temperatureDescription_get( jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx, char **temperatureDescription_val_ptr_ptr, size_t *temperatureDescription_val_ptr_len_ptr );
    int temperatureStatus_get( jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx, char **temperatureStatus_val_ptr_ptr, size_t *temperatureStatus_val_ptr_len_ptr );
    int temperatureValue_get( jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx, long * temperatureValue_val_ptr );
    int temperatureUnit_get( jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx, char **temperatureUnit_val_ptr_ptr, size_t *temperatureUnit_val_ptr_len_ptr );


int jbodDevTemperatureTable_indexes_set_tbl_idx(jbodDevTemperatureTable_mib_index *tbl_idx, long temperatureIndex_val);
int jbodDevTemperatureTable_indexes_set(jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx, long temperatureIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* JBODDEVTEMPERATURETABLE_DATA_GET_H */
/** @} */
