/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "jbodDevFanTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement jbodDevFanTable get routines.
 * TODO:240:M: Implement jbodDevFanTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevFanTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevFanTable is subid 4 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.4, length: 10
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement jbodDevFanTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param fanIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
jbodDevFanTable_indexes_set_tbl_idx(jbodDevFanTable_mib_index *tbl_idx, long fanIndex_val)
{
    DEBUGMSGTL(("verbose:jbodDevFanTable:jbodDevFanTable_indexes_set_tbl_idx","called\n"));

    /* fanIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/R/d/h */
    tbl_idx->fanIndex = fanIndex_val;
    

    return MFD_SUCCESS;
} /* jbodDevFanTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
jbodDevFanTable_indexes_set(jbodDevFanTable_rowreq_ctx *rowreq_ctx, long fanIndex_val)
{
    DEBUGMSGTL(("verbose:jbodDevFanTable:jbodDevFanTable_indexes_set","called\n"));

    if(MFD_SUCCESS != jbodDevFanTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , fanIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != jbodDevFanTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* jbodDevFanTable_indexes_set */


/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevFanEntry.fanDescription
 * fanDescription is subid 2 of jbodDevFanEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.4.1.2
 * Description:
Describe the fan sensor
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the fanDescription data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param fanDescription_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param fanDescription_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by fanDescription.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*fanDescription_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update fanDescription_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
fanDescription_get( jbodDevFanTable_rowreq_ctx *rowreq_ctx, char **fanDescription_val_ptr_ptr, size_t *fanDescription_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != fanDescription_val_ptr_ptr) && (NULL != *fanDescription_val_ptr_ptr));
   netsnmp_assert( NULL != fanDescription_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevFanTable:fanDescription_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the fanDescription data.
 * copy (* fanDescription_val_ptr_ptr ) data and (* fanDescription_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for fanDescription data
     */
    if ((NULL == (* fanDescription_val_ptr_ptr )) ||
        ((* fanDescription_val_ptr_len_ptr ) <
         (rowreq_ctx->data.fanDescription_len* sizeof(rowreq_ctx->data.fanDescription[0])))) {
        /*
         * allocate space for fanDescription data
         */
        (* fanDescription_val_ptr_ptr ) = malloc(rowreq_ctx->data.fanDescription_len* sizeof(rowreq_ctx->data.fanDescription[0]));
        if(NULL == (* fanDescription_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.fanDescription)\n");
            return MFD_ERROR;
        }
    }
    (* fanDescription_val_ptr_len_ptr ) = rowreq_ctx->data.fanDescription_len* sizeof(rowreq_ctx->data.fanDescription[0]);
    memcpy( (* fanDescription_val_ptr_ptr ), rowreq_ctx->data.fanDescription, rowreq_ctx->data.fanDescription_len* sizeof(rowreq_ctx->data.fanDescription[0]) );

    return MFD_SUCCESS;
} /* fanDescription_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevFanEntry.fanStatus
 * fanStatus is subid 3 of jbodDevFanEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.4.1.3
 * Description:
Describe the fan sensor status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the fanStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param fanStatus_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param fanStatus_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by fanStatus.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*fanStatus_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update fanStatus_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
fanStatus_get( jbodDevFanTable_rowreq_ctx *rowreq_ctx, char **fanStatus_val_ptr_ptr, size_t *fanStatus_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != fanStatus_val_ptr_ptr) && (NULL != *fanStatus_val_ptr_ptr));
   netsnmp_assert( NULL != fanStatus_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevFanTable:fanStatus_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the fanStatus data.
 * copy (* fanStatus_val_ptr_ptr ) data and (* fanStatus_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for fanStatus data
     */
    if ((NULL == (* fanStatus_val_ptr_ptr )) ||
        ((* fanStatus_val_ptr_len_ptr ) <
         (rowreq_ctx->data.fanStatus_len* sizeof(rowreq_ctx->data.fanStatus[0])))) {
        /*
         * allocate space for fanStatus data
         */
        (* fanStatus_val_ptr_ptr ) = malloc(rowreq_ctx->data.fanStatus_len* sizeof(rowreq_ctx->data.fanStatus[0]));
        if(NULL == (* fanStatus_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.fanStatus)\n");
            return MFD_ERROR;
        }
    }
    (* fanStatus_val_ptr_len_ptr ) = rowreq_ctx->data.fanStatus_len* sizeof(rowreq_ctx->data.fanStatus[0]);
    memcpy( (* fanStatus_val_ptr_ptr ), rowreq_ctx->data.fanStatus, rowreq_ctx->data.fanStatus_len* sizeof(rowreq_ctx->data.fanStatus[0]) );

    return MFD_SUCCESS;
} /* fanStatus_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevFanEntry.fanValue
 * fanValue is subid 4 of jbodDevFanEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.4.1.4
 * Description:
Describe the sensor fan value
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the fanValue data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param fanValue_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
fanValue_get( jbodDevFanTable_rowreq_ctx *rowreq_ctx, long * fanValue_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != fanValue_val_ptr );


    DEBUGMSGTL(("verbose:jbodDevFanTable:fanValue_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the fanValue data.
 * copy (* fanValue_val_ptr ) from rowreq_ctx->data
 */
    (* fanValue_val_ptr ) = rowreq_ctx->data.fanValue;

    return MFD_SUCCESS;
} /* fanValue_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevFanEntry.fanUnit
 * fanUnit is subid 5 of jbodDevFanEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.4.1.5
 * Description:
Describe the fan speed unit: RPM
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the fanUnit data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param fanUnit_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param fanUnit_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by fanUnit.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*fanUnit_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update fanUnit_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
fanUnit_get( jbodDevFanTable_rowreq_ctx *rowreq_ctx, char **fanUnit_val_ptr_ptr, size_t *fanUnit_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != fanUnit_val_ptr_ptr) && (NULL != *fanUnit_val_ptr_ptr));
   netsnmp_assert( NULL != fanUnit_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevFanTable:fanUnit_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the fanUnit data.
 * copy (* fanUnit_val_ptr_ptr ) data and (* fanUnit_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for fanUnit data
     */
    if ((NULL == (* fanUnit_val_ptr_ptr )) ||
        ((* fanUnit_val_ptr_len_ptr ) <
         (rowreq_ctx->data.fanUnit_len* sizeof(rowreq_ctx->data.fanUnit[0])))) {
        /*
         * allocate space for fanUnit data
         */
        (* fanUnit_val_ptr_ptr ) = malloc(rowreq_ctx->data.fanUnit_len* sizeof(rowreq_ctx->data.fanUnit[0]));
        if(NULL == (* fanUnit_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.fanUnit)\n");
            return MFD_ERROR;
        }
    }
    (* fanUnit_val_ptr_len_ptr ) = rowreq_ctx->data.fanUnit_len* sizeof(rowreq_ctx->data.fanUnit[0]);
    memcpy( (* fanUnit_val_ptr_ptr ), rowreq_ctx->data.fanUnit, rowreq_ctx->data.fanUnit_len* sizeof(rowreq_ctx->data.fanUnit[0]) );

    return MFD_SUCCESS;
} /* fanUnit_get */



/** @} */
