/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "jbodDevTemperatureTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "jbodDevTemperatureTable_interface.h"

netsnmp_feature_require(baby_steps)
netsnmp_feature_require(row_merge)
netsnmp_feature_require(check_all_requests_error)

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevTemperatureTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevTemperatureTable is subid 2 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.2, length: 10
*/
typedef struct jbodDevTemperatureTable_interface_ctx_s {

   netsnmp_container              *container;

   jbodDevTemperatureTable_registration *      user_ctx;
   
   netsnmp_table_registration_info  tbl_info;

   netsnmp_baby_steps_access_methods access_multiplexer;

} jbodDevTemperatureTable_interface_ctx;

static jbodDevTemperatureTable_interface_ctx jbodDevTemperatureTable_if_ctx;

static void _jbodDevTemperatureTable_container_init(
    jbodDevTemperatureTable_interface_ctx *if_ctx);
static void _jbodDevTemperatureTable_container_shutdown(
    jbodDevTemperatureTable_interface_ctx *if_ctx);


netsnmp_container *
jbodDevTemperatureTable_container_get( void )
{
    return jbodDevTemperatureTable_if_ctx.container;
}

jbodDevTemperatureTable_registration *
jbodDevTemperatureTable_registration_get( void )
{
    return jbodDevTemperatureTable_if_ctx.user_ctx;
}

jbodDevTemperatureTable_registration *
jbodDevTemperatureTable_registration_set( jbodDevTemperatureTable_registration * newreg )
{
    jbodDevTemperatureTable_registration * old = jbodDevTemperatureTable_if_ctx.user_ctx;
    jbodDevTemperatureTable_if_ctx.user_ctx = newreg;
    return old;
}

int
jbodDevTemperatureTable_container_size( void )
{
    return CONTAINER_SIZE(jbodDevTemperatureTable_if_ctx.container);
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_jbodDevTemperatureTable_pre_request;
static Netsnmp_Node_Handler _mfd_jbodDevTemperatureTable_post_request;
static Netsnmp_Node_Handler _mfd_jbodDevTemperatureTable_object_lookup;
static Netsnmp_Node_Handler _mfd_jbodDevTemperatureTable_get_values;
/**
 * @internal
 * Initialize the table jbodDevTemperatureTable 
 *    (Define its contents and how it's structured)
 */
void
_jbodDevTemperatureTable_initialize_interface(jbodDevTemperatureTable_registration * reg_ptr,  u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &jbodDevTemperatureTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info = &jbodDevTemperatureTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int    mfd_modes = 0;

    DEBUGMSGTL(("internal:jbodDevTemperatureTable:_jbodDevTemperatureTable_initialize_interface","called\n"));


    /*************************************************
     *
     * save interface context for jbodDevTemperatureTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info,
                                  ASN_INTEGER, /** index: temperatureIndex */
                             0);

    /*  Define the minimum and maximum accessible columns.  This
        optimizes retrieval. */
    tbl_info->min_column = JBODDEVTEMPERATURETABLE_MIN_COL;
    tbl_info->max_column = JBODDEVTEMPERATURETABLE_MAX_COL;

    /*
     * save users context
     */
    jbodDevTemperatureTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    jbodDevTemperatureTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _jbodDevTemperatureTable_container_init(&jbodDevTemperatureTable_if_ctx);
    if (NULL == jbodDevTemperatureTable_if_ctx.container) {
        snmp_log(LOG_ERR,"could not initialize container for jbodDevTemperatureTable\n");
        return;
    }
    
    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_jbodDevTemperatureTable_object_lookup;
    access_multiplexer->get_values = _mfd_jbodDevTemperatureTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_jbodDevTemperatureTable_pre_request;
    access_multiplexer->post_request = _mfd_jbodDevTemperatureTable_post_request;

#ifndef NETSNMP_DISABLE_SET_SUPPORT
#endif

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("jbodDevTemperatureTable:init_jbodDevTemperatureTable",
                "Registering jbodDevTemperatureTable as a mibs-for-dummies table.\n"));		 
    handler = netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo = netsnmp_handler_registration_create("jbodDevTemperatureTable", handler,
                                                  jbodDevTemperatureTable_oid,
                                                  jbodDevTemperatureTable_oid_size,
                                                  HANDLER_CAN_BABY_STEP |
#if (defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
                                                  HANDLER_CAN_RONLY
#else
                                                  HANDLER_CAN_RONLY
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
                                                  );
    if(NULL == reginfo) {
        snmp_log(LOG_ERR,"error registering table jbodDevTemperatureTable\n");
        return;
    }
    reginfo->my_reg_void = &jbodDevTemperatureTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if( access_multiplexer->object_lookup )
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if( access_multiplexer->pre_request )
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if( access_multiplexer->post_request )
        mfd_modes |= BABY_STEP_POST_REQUEST;
    
#if !(defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
    if( access_multiplexer->set_values )
        mfd_modes |= BABY_STEP_SET_VALUES;
    if( access_multiplexer->irreversible_commit )
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if( access_multiplexer->object_syntax_checks )
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if( access_multiplexer->undo_setup )
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if( access_multiplexer->undo_cleanup )
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if( access_multiplexer->undo_sets )
        mfd_modes |= BABY_STEP_UNDO_SETS;
    
    if( access_multiplexer->row_creation )
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if( access_multiplexer->consistency_checks )
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if( access_multiplexer->commit )
        mfd_modes |= BABY_STEP_COMMIT;
    if( access_multiplexer->undo_commit )
        mfd_modes |= BABY_STEP_UNDO_COMMIT;
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
    
    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            jbodDevTemperatureTable_if_ctx.container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler( reginfo, handler );

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

} /* _jbodDevTemperatureTable_initialize_interface */

/**
 * @internal
 * Shutdown the table jbodDevTemperatureTable
 */
void
_jbodDevTemperatureTable_shutdown_interface(jbodDevTemperatureTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _jbodDevTemperatureTable_container_shutdown(&jbodDevTemperatureTable_if_ctx);
}

void
jbodDevTemperatureTable_valid_columns_set(netsnmp_column_info *vc)
{
    jbodDevTemperatureTable_if_ctx.tbl_info.valid_columns = vc;
} /* jbodDevTemperatureTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
jbodDevTemperatureTable_index_to_oid(netsnmp_index *oid_idx,
                         jbodDevTemperatureTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * temperatureIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/R/d/h
     */
    netsnmp_variable_list var_temperatureIndex;

    /*
     * set up varbinds
     */
    memset( &var_temperatureIndex, 0x00, sizeof(var_temperatureIndex) );
    var_temperatureIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_temperatureIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:jbodDevTemperatureTable:jbodDevTemperatureTable_index_to_oid","called\n"));

        /* temperatureIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/R/d/h */
    snmp_set_var_value(&var_temperatureIndex, &mib_idx->temperatureIndex, sizeof(mib_idx->temperatureIndex));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                           NULL, 0, &var_temperatureIndex);
    if(err)
        snmp_log(LOG_ERR,"error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_temperatureIndex );

    return err;
} /* jbodDevTemperatureTable_index_to_oid */

/**
 * extract jbodDevTemperatureTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
jbodDevTemperatureTable_index_from_oid(netsnmp_index *oid_idx,
                         jbodDevTemperatureTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * temperatureIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/R/d/h
     */
    netsnmp_variable_list var_temperatureIndex;

    /*
     * set up varbinds
     */
    memset( &var_temperatureIndex, 0x00, sizeof(var_temperatureIndex) );
    var_temperatureIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_temperatureIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:jbodDevTemperatureTable:jbodDevTemperatureTable_index_from_oid","called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes( oid_idx->oids, oid_idx->len,
                             &var_temperatureIndex );
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
    mib_idx->temperatureIndex = *((long *)var_temperatureIndex.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_temperatureIndex );

    return err;
} /* jbodDevTemperatureTable_index_from_oid */


/* *********************************************************************
 * @internal
 * allocate resources for a jbodDevTemperatureTable_rowreq_ctx
 */
jbodDevTemperatureTable_rowreq_ctx *
jbodDevTemperatureTable_allocate_rowreq_ctx(void *user_init_ctx)
{
    jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx =
                  SNMP_MALLOC_TYPEDEF(jbodDevTemperatureTable_rowreq_ctx);

    DEBUGMSGTL(("internal:jbodDevTemperatureTable:jbodDevTemperatureTable_allocate_rowreq_ctx","called\n"));

    if(NULL == rowreq_ctx) {
        snmp_log(LOG_ERR,"Couldn't allocate memory for a "
                 "jbodDevTemperatureTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->jbodDevTemperatureTable_data_list = NULL;

    /*
     * if we allocated data, call init routine
     */
    if (!(rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER)) {
        if(SNMPERR_SUCCESS !=
            jbodDevTemperatureTable_rowreq_ctx_init(rowreq_ctx, user_init_ctx)) {
           jbodDevTemperatureTable_release_rowreq_ctx(rowreq_ctx);
           rowreq_ctx = NULL;
        }
    }

    return rowreq_ctx;
} /* jbodDevTemperatureTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a jbodDevTemperatureTable_rowreq_ctx
 */
void
jbodDevTemperatureTable_release_rowreq_ctx(jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("internal:jbodDevTemperatureTable:jbodDevTemperatureTable_release_rowreq_ctx","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    jbodDevTemperatureTable_rowreq_ctx_cleanup(rowreq_ctx);

    /*
     * free index oid pointer
     */
    if(rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
} /* jbodDevTemperatureTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_jbodDevTemperatureTable_pre_request(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *agtreq_info,
                            netsnmp_request_info *requests)
{
    int rc;

    DEBUGMSGTL(("internal:jbodDevTemperatureTable:_mfd_jbodDevTemperatureTable_pre_request",
                "called\n"));
    
    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:jbodDevTemperatureTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }
        
    rc = jbodDevTemperatureTable_pre_request(jbodDevTemperatureTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("jbodDevTemperatureTable","error %d from "
                    "jbodDevTemperatureTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_jbodDevTemperatureTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_jbodDevTemperatureTable_post_request(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx = (jbodDevTemperatureTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    int rc, packet_rc;

    DEBUGMSGTL(("internal:jbodDevTemperatureTable:_mfd_jbodDevTemperatureTable_post_request",
                "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        jbodDevTemperatureTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:jbodDevTemperatureTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }
    
    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    rc = jbodDevTemperatureTable_post_request(jbodDevTemperatureTable_if_ctx.user_ctx,packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("jbodDevTemperatureTable","error %d from "
                    "jbodDevTemperatureTable_post_request\n", rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_jbodDevTemperatureTable_post_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_jbodDevTemperatureTable_object_lookup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc = SNMP_ERR_NOERROR;
    jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx = (jbodDevTemperatureTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:jbodDevTemperatureTable:_mfd_jbodDevTemperatureTable_object_lookup","called\n"));

    /*
     * get our context from mfd
     * jbodDevTemperatureTable_interface_ctx *if_ctx =
     *             (jbodDevTemperatureTable_interface_ctx *)reginfo->my_reg_void;
     */

    if(NULL == rowreq_ctx) {
        rc = SNMP_ERR_NOCREATION;
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        jbodDevTemperatureTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
} /* _mfd_jbodDevTemperatureTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_jbodDevTemperatureTable_get_column( jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:jbodDevTemperatureTable:_mfd_jbodDevTemperatureTable_get_column",
                "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* temperatureDescription(2)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_TEMPERATUREDESCRIPTION:
    var->type = ASN_OCTET_STR;
rc = temperatureDescription_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* temperatureStatus(3)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_TEMPERATURESTATUS:
    var->type = ASN_OCTET_STR;
rc = temperatureStatus_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* temperatureValue(4)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_TEMPERATUREVALUE:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = temperatureValue_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* temperatureUnit(5)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_TEMPERATUREUNIT:
    var->type = ASN_OCTET_STR;
rc = temperatureUnit_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

     default:
        if (JBODDEVTEMPERATURETABLE_MIN_COL <= column && column <= JBODDEVTEMPERATURETABLE_MAX_COL) {
            DEBUGMSGTL(("internal:jbodDevTemperatureTable:_mfd_jbodDevTemperatureTable_get_column",
                "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                "unknown column %d in _jbodDevTemperatureTable_get_column\n", column);
        }
        break;
    }

    return rc;
} /* _jbodDevTemperatureTable_get_column */

int
_mfd_jbodDevTemperatureTable_get_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx = (jbodDevTemperatureTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    u_char                     * old_string;
    void                      (*dataFreeHook)(void *);
    int                        rc;

    DEBUGMSGTL(("internal:jbodDevTemperatureTable:_mfd_jbodDevTemperatureTable_get_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if(NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }
        else if(requests->requestvb->buf == requests->requestvb->val.string) {
            if(requests->requestvb->val_len != sizeof(requests->requestvb->buf))
                requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _jbodDevTemperatureTable_get_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            if(MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        }
        else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR,"NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if(rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if(old_string && (old_string != requests->requestvb->buf) &&
           (requests->requestvb->val.string != old_string)) {
            if(dataFreeHook)
                (*dataFreeHook)(old_string);
            else
                free(old_string);
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_jbodDevTemperatureTable_get_values */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*
 * SET PROCESSING NOT APPLICABLE (per MIB or user setting)
 */
/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
/**
 * @internal
 */
static void
_container_item_free(jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx, void *context)
{
    DEBUGMSGTL(("internal:jbodDevTemperatureTable:_container_item_free","called\n"));

    if(NULL == rowreq_ctx)
        return;

    jbodDevTemperatureTable_release_rowreq_ctx(rowreq_ctx);
} /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("internal:jbodDevTemperatureTable:_container_free","called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR, "invalid container in jbodDevTemperatureTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    jbodDevTemperatureTable_container_free(container);
    
    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)_container_item_free,
                    NULL);
} /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_jbodDevTemperatureTable_container_init(jbodDevTemperatureTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:jbodDevTemperatureTable:_jbodDevTemperatureTable_container_init","called\n"));

    /*
     * container init
     */    
    jbodDevTemperatureTable_container_init(&if_ctx->container);
    if(NULL == if_ctx->container) {
        if_ctx->container = netsnmp_container_find("jbodDevTemperatureTable:table_container");
        if(NULL != if_ctx->container) {
            /*
             * When reporting container management errors, we log the container's
             * name, so set it here.
             */
            if_ctx->container->container_name = strdup("jbodDevTemperatureTable");
        }
    }
    if(NULL == if_ctx->container) {
        snmp_log(LOG_ERR,"error creating container in "
                 "jbodDevTemperatureTable_container_init\n");
        return;
    }

} /* _jbodDevTemperatureTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_jbodDevTemperatureTable_container_shutdown(jbodDevTemperatureTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:jbodDevTemperatureTable:_jbodDevTemperatureTable_container_shutdown","called\n"));

    jbodDevTemperatureTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

} /* _jbodDevTemperatureTable_container_shutdown */


jbodDevTemperatureTable_rowreq_ctx *
jbodDevTemperatureTable_row_find_by_mib_index(jbodDevTemperatureTable_mib_index *mib_idx)
{
    jbodDevTemperatureTable_rowreq_ctx   *rowreq_ctx;
    oid                      oid_tmp[MAX_OID_LEN];
    netsnmp_index            oid_idx;
    int                      rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp)/sizeof(oid);

    /*
     * convert
     */
    rc = jbodDevTemperatureTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx = (jbodDevTemperatureTable_rowreq_ctx*)CONTAINER_FIND(jbodDevTemperatureTable_if_ctx.container, &oid_idx);

    return rowreq_ctx;
}

