/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef JBODDEVTEMPERATURETABLE_OIDS_H
#define JBODDEVTEMPERATURETABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table jbodDevTemperatureTable */
#define JBODDEVTEMPERATURETABLE_OID              1,3,6,1,4,1,47464,1,2,2


#define COLUMN_TEMPERATUREINDEX         1
    
#define COLUMN_TEMPERATUREDESCRIPTION         2
    
#define COLUMN_TEMPERATURESTATUS         3
    
#define COLUMN_TEMPERATUREVALUE         4
    
#define COLUMN_TEMPERATUREUNIT         5
    

#define JBODDEVTEMPERATURETABLE_MIN_COL   COLUMN_TEMPERATUREDESCRIPTION
#define JBODDEVTEMPERATURETABLE_MAX_COL   COLUMN_TEMPERATUREUNIT
    


#ifdef __cplusplus
}
#endif

#endif /* JBODDEVTEMPERATURETABLE_OIDS_H */
