/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef JBODDEVBASE_H
#define JBODDEVBASE_H

/* function declarations */
void init_jbodDevBase(void);
Netsnmp_Node_Handler handle_jbodDevSerial;
Netsnmp_Node_Handler handle_jbodDevSwVersion;
Netsnmp_Node_Handler handle_jbodDevMacAddress;
Netsnmp_Node_Handler handle_jbodDevDateTime;
Netsnmp_Node_Handler handle_jbodDevExpanderPHwVersion;
Netsnmp_Node_Handler handle_jbodDevExpanderSHwVersion;
Netsnmp_Node_Handler handle_jbodDevExpanderPFwVersion;
Netsnmp_Node_Handler handle_jbodDevExpanderSFwVersion;
Netsnmp_Node_Handler handle_jbodDevExpanderPMfgVersion;
Netsnmp_Node_Handler handle_jbodDevExpanderSMfgVersion;
Netsnmp_Node_Handler handle_jbodDevSwUpgradeName;
Netsnmp_Node_Handler handle_jbodDevSwUpgradeServer;
Netsnmp_Node_Handler handle_jbodDevSwUpgrade;
Netsnmp_Node_Handler handle_jbodDevResetNow;

#endif /* JBODDEVBASE_H */
