/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
#ifndef JBODDEVVOLTAGETABLE_H
#define JBODDEVVOLTAGETABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(INWIN-JBOD-MIB)
config_require(INWIN-JBOD-MIB/jbodDevVoltageTable/jbodDevVoltageTable_interface)
config_require(INWIN-JBOD-MIB/jbodDevVoltageTable/jbodDevVoltageTable_data_access)
config_require(INWIN-JBOD-MIB/jbodDevVoltageTable/jbodDevVoltageTable_data_get)
config_require(INWIN-JBOD-MIB/jbodDevVoltageTable/jbodDevVoltageTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for jbodDevVoltageTable */
#include "jbodDevVoltageTable_oids.h"

/* enum definions */
#include "jbodDevVoltageTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_jbodDevVoltageTable(void);
void shutdown_jbodDevVoltageTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevVoltageTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevVoltageTable is subid 3 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.3, length: 10
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review jbodDevVoltageTable registration context.
     */
typedef netsnmp_data_list jbodDevVoltageTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review jbodDevVoltageTable data context structure.
 * This structure is used to represent the data for jbodDevVoltageTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * jbodDevVoltageTable.
 */
typedef struct jbodDevVoltageTable_data_s {
    
        /*
         * voltageDescription(2)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   voltageDescription[128];
size_t      voltageDescription_len; /* # of char elements, not bytes */
    
        /*
         * voltageStatus(3)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   voltageStatus[128];
size_t      voltageStatus_len; /* # of char elements, not bytes */
    
        /*
         * voltageValue(4)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   voltageValue;
    
        /*
         * voltageUnit(5)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   voltageUnit[128];
size_t      voltageUnit_len; /* # of char elements, not bytes */
    
} jbodDevVoltageTable_data;


/*
 * TODO:120:r: |-> Review jbodDevVoltageTable mib index.
 * This structure is used to represent the index for jbodDevVoltageTable.
 */
typedef struct jbodDevVoltageTable_mib_index_s {

        /*
         * voltageIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/R/d/h
         */
   long   voltageIndex;


} jbodDevVoltageTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review jbodDevVoltageTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_jbodDevVoltageTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review jbodDevVoltageTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * jbodDevVoltageTable_rowreq_ctx pointer.
 */
typedef struct jbodDevVoltageTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_jbodDevVoltageTable_IDX_LEN];
    
    jbodDevVoltageTable_mib_index        tbl_idx;
    
    jbodDevVoltageTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to jbodDevVoltageTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *jbodDevVoltageTable_data_list;

} jbodDevVoltageTable_rowreq_ctx;

typedef struct jbodDevVoltageTable_ref_rowreq_ctx_s {
    jbodDevVoltageTable_rowreq_ctx *rowreq_ctx;
} jbodDevVoltageTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int jbodDevVoltageTable_pre_request(jbodDevVoltageTable_registration * user_context);
    int jbodDevVoltageTable_post_request(jbodDevVoltageTable_registration * user_context,
        int rc);

    int jbodDevVoltageTable_rowreq_ctx_init(jbodDevVoltageTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void jbodDevVoltageTable_rowreq_ctx_cleanup(jbodDevVoltageTable_rowreq_ctx *rowreq_ctx);


    jbodDevVoltageTable_rowreq_ctx *
                  jbodDevVoltageTable_row_find_by_mib_index(jbodDevVoltageTable_mib_index *mib_idx);

extern const oid jbodDevVoltageTable_oid[];
extern const int jbodDevVoltageTable_oid_size;


#include "jbodDevVoltageTable_interface.h"
#include "jbodDevVoltageTable_data_access.h"
#include "jbodDevVoltageTable_data_get.h"
#include "jbodDevVoltageTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* JBODDEVVOLTAGETABLE_H */
/** @} */
