/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
#ifndef JBODDEVLOGTABLE_H
#define JBODDEVLOGTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(INWIN-JBOD-MIB)
config_require(INWIN-JBOD-MIB/jbodDevLogTable/jbodDevLogTable_interface)
config_require(INWIN-JBOD-MIB/jbodDevLogTable/jbodDevLogTable_data_access)
config_require(INWIN-JBOD-MIB/jbodDevLogTable/jbodDevLogTable_data_get)
config_require(INWIN-JBOD-MIB/jbodDevLogTable/jbodDevLogTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for jbodDevLogTable */
#include "jbodDevLogTable_oids.h"

/* enum definions */
#include "jbodDevLogTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_jbodDevLogTable(void);
void shutdown_jbodDevLogTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevLogTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevLogTable is subid 6 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.6, length: 10
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review jbodDevLogTable registration context.
     */
typedef netsnmp_data_list jbodDevLogTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review jbodDevLogTable data context structure.
 * This structure is used to represent the data for jbodDevLogTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * jbodDevLogTable.
 */
typedef struct jbodDevLogTable_data_s {
    
        /*
         * logTime(2)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   logTime[128];
size_t      logTime_len; /* # of char elements, not bytes */
    
        /*
         * logType(3)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   logType[128];
size_t      logType_len; /* # of char elements, not bytes */
    
        /*
         * logDescription(4)/SnmpAdminString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   logDescription[128];
size_t      logDescription_len; /* # of char elements, not bytes */
    
} jbodDevLogTable_data;


/*
 * TODO:120:r: |-> Review jbodDevLogTable mib index.
 * This structure is used to represent the index for jbodDevLogTable.
 */
typedef struct jbodDevLogTable_mib_index_s {

        /*
         * logIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/R/d/h
         */
   long   logIndex;


} jbodDevLogTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review jbodDevLogTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_jbodDevLogTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review jbodDevLogTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * jbodDevLogTable_rowreq_ctx pointer.
 */
typedef struct jbodDevLogTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_jbodDevLogTable_IDX_LEN];
    
    jbodDevLogTable_mib_index        tbl_idx;
    
    jbodDevLogTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to jbodDevLogTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *jbodDevLogTable_data_list;

} jbodDevLogTable_rowreq_ctx;

typedef struct jbodDevLogTable_ref_rowreq_ctx_s {
    jbodDevLogTable_rowreq_ctx *rowreq_ctx;
} jbodDevLogTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int jbodDevLogTable_pre_request(jbodDevLogTable_registration * user_context);
    int jbodDevLogTable_post_request(jbodDevLogTable_registration * user_context,
        int rc);

    int jbodDevLogTable_rowreq_ctx_init(jbodDevLogTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void jbodDevLogTable_rowreq_ctx_cleanup(jbodDevLogTable_rowreq_ctx *rowreq_ctx);


    jbodDevLogTable_rowreq_ctx *
                  jbodDevLogTable_row_find_by_mib_index(jbodDevLogTable_mib_index *mib_idx);

extern const oid jbodDevLogTable_oid[];
extern const int jbodDevLogTable_oid_size;


#include "jbodDevLogTable_interface.h"
#include "jbodDevLogTable_data_access.h"
#include "jbodDevLogTable_data_get.h"
#include "jbodDevLogTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* JBODDEVLOGTABLE_H */
/** @} */
