/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef JBODDEVDISKTABLE_OIDS_H
#define JBODDEVDISKTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table jbodDevDiskTable */
#define JBODDEVDISKTABLE_OID              1,3,6,1,4,1,47464,1,2,5


#define COLUMN_DISKINDEX         1
    
#define COLUMN_PHYID         2
    
#define COLUMN_NLRATE         3
    
#define COLUMN_SASADDRESS         4
    
#define COLUMN_DISKTYPE         5
    
#define COLUMN_STATUS         6
    

#define JBODDEVDISKTABLE_MIN_COL   COLUMN_PHYID
#define JBODDEVDISKTABLE_MAX_COL   COLUMN_STATUS
    


#ifdef __cplusplus
}
#endif

#endif /* JBODDEVDISKTABLE_OIDS_H */
