/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef JBODDEVFANTABLE_INTERFACE_H
#define JBODDEVFANTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "jbodDevFanTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _jbodDevFanTable_initialize_interface(jbodDevFanTable_registration * user_ctx,
                                    u_long flags);
void _jbodDevFanTable_shutdown_interface(jbodDevFanTable_registration * user_ctx);

jbodDevFanTable_registration *
jbodDevFanTable_registration_get( void );

jbodDevFanTable_registration *
jbodDevFanTable_registration_set( jbodDevFanTable_registration * newreg );

netsnmp_container *jbodDevFanTable_container_get( void );
int jbodDevFanTable_container_size( void );

    jbodDevFanTable_rowreq_ctx * jbodDevFanTable_allocate_rowreq_ctx(void *);
void jbodDevFanTable_release_rowreq_ctx(jbodDevFanTable_rowreq_ctx *rowreq_ctx);

int jbodDevFanTable_index_to_oid(netsnmp_index *oid_idx,
                            jbodDevFanTable_mib_index *mib_idx);
int jbodDevFanTable_index_from_oid(netsnmp_index *oid_idx,
                              jbodDevFanTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void jbodDevFanTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* JBODDEVFANTABLE_INTERFACE_H */
/** @} */
