/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "jbodDevVoltageTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement jbodDevVoltageTable get routines.
 * TODO:240:M: Implement jbodDevVoltageTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevVoltageTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevVoltageTable is subid 3 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.3, length: 10
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement jbodDevVoltageTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param voltageIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
jbodDevVoltageTable_indexes_set_tbl_idx(jbodDevVoltageTable_mib_index *tbl_idx, long voltageIndex_val)
{
    DEBUGMSGTL(("verbose:jbodDevVoltageTable:jbodDevVoltageTable_indexes_set_tbl_idx","called\n"));

    /* voltageIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/R/d/h */
    tbl_idx->voltageIndex = voltageIndex_val;
    

    return MFD_SUCCESS;
} /* jbodDevVoltageTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
jbodDevVoltageTable_indexes_set(jbodDevVoltageTable_rowreq_ctx *rowreq_ctx, long voltageIndex_val)
{
    DEBUGMSGTL(("verbose:jbodDevVoltageTable:jbodDevVoltageTable_indexes_set","called\n"));

    if(MFD_SUCCESS != jbodDevVoltageTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , voltageIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != jbodDevVoltageTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* jbodDevVoltageTable_indexes_set */


/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevVoltageEntry.voltageDescription
 * voltageDescription is subid 2 of jbodDevVoltageEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.3.1.2
 * Description:
Describe the voltage sensor
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the voltageDescription data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param voltageDescription_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param voltageDescription_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by voltageDescription.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*voltageDescription_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update voltageDescription_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
voltageDescription_get( jbodDevVoltageTable_rowreq_ctx *rowreq_ctx, char **voltageDescription_val_ptr_ptr, size_t *voltageDescription_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != voltageDescription_val_ptr_ptr) && (NULL != *voltageDescription_val_ptr_ptr));
   netsnmp_assert( NULL != voltageDescription_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevVoltageTable:voltageDescription_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the voltageDescription data.
 * copy (* voltageDescription_val_ptr_ptr ) data and (* voltageDescription_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for voltageDescription data
     */
    if ((NULL == (* voltageDescription_val_ptr_ptr )) ||
        ((* voltageDescription_val_ptr_len_ptr ) <
         (rowreq_ctx->data.voltageDescription_len* sizeof(rowreq_ctx->data.voltageDescription[0])))) {
        /*
         * allocate space for voltageDescription data
         */
        (* voltageDescription_val_ptr_ptr ) = malloc(rowreq_ctx->data.voltageDescription_len* sizeof(rowreq_ctx->data.voltageDescription[0]));
        if(NULL == (* voltageDescription_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.voltageDescription)\n");
            return MFD_ERROR;
        }
    }
    (* voltageDescription_val_ptr_len_ptr ) = rowreq_ctx->data.voltageDescription_len* sizeof(rowreq_ctx->data.voltageDescription[0]);
    memcpy( (* voltageDescription_val_ptr_ptr ), rowreq_ctx->data.voltageDescription, rowreq_ctx->data.voltageDescription_len* sizeof(rowreq_ctx->data.voltageDescription[0]) );

    return MFD_SUCCESS;
} /* voltageDescription_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevVoltageEntry.voltageStatus
 * voltageStatus is subid 3 of jbodDevVoltageEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.3.1.3
 * Description:
Describe the voltage sensor status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the voltageStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param voltageStatus_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param voltageStatus_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by voltageStatus.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*voltageStatus_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update voltageStatus_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
voltageStatus_get( jbodDevVoltageTable_rowreq_ctx *rowreq_ctx, char **voltageStatus_val_ptr_ptr, size_t *voltageStatus_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != voltageStatus_val_ptr_ptr) && (NULL != *voltageStatus_val_ptr_ptr));
   netsnmp_assert( NULL != voltageStatus_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevVoltageTable:voltageStatus_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the voltageStatus data.
 * copy (* voltageStatus_val_ptr_ptr ) data and (* voltageStatus_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for voltageStatus data
     */
    if ((NULL == (* voltageStatus_val_ptr_ptr )) ||
        ((* voltageStatus_val_ptr_len_ptr ) <
         (rowreq_ctx->data.voltageStatus_len* sizeof(rowreq_ctx->data.voltageStatus[0])))) {
        /*
         * allocate space for voltageStatus data
         */
        (* voltageStatus_val_ptr_ptr ) = malloc(rowreq_ctx->data.voltageStatus_len* sizeof(rowreq_ctx->data.voltageStatus[0]));
        if(NULL == (* voltageStatus_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.voltageStatus)\n");
            return MFD_ERROR;
        }
    }
    (* voltageStatus_val_ptr_len_ptr ) = rowreq_ctx->data.voltageStatus_len* sizeof(rowreq_ctx->data.voltageStatus[0]);
    memcpy( (* voltageStatus_val_ptr_ptr ), rowreq_ctx->data.voltageStatus, rowreq_ctx->data.voltageStatus_len* sizeof(rowreq_ctx->data.voltageStatus[0]) );

    return MFD_SUCCESS;
} /* voltageStatus_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevVoltageEntry.voltageValue
 * voltageValue is subid 4 of jbodDevVoltageEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.3.1.4
 * Description:
Describe the sensor voltage value
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the voltageValue data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param voltageValue_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
voltageValue_get( jbodDevVoltageTable_rowreq_ctx *rowreq_ctx, long * voltageValue_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != voltageValue_val_ptr );


    DEBUGMSGTL(("verbose:jbodDevVoltageTable:voltageValue_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the voltageValue data.
 * copy (* voltageValue_val_ptr ) from rowreq_ctx->data
 */
    (* voltageValue_val_ptr ) = rowreq_ctx->data.voltageValue;

    return MFD_SUCCESS;
} /* voltageValue_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevVoltageEntry.voltageUnit
 * voltageUnit is subid 5 of jbodDevVoltageEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.3.1.5
 * Description:
Describe the voltage unit (maybe 1/10)
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the voltageUnit data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param voltageUnit_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param voltageUnit_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by voltageUnit.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*voltageUnit_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update voltageUnit_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
voltageUnit_get( jbodDevVoltageTable_rowreq_ctx *rowreq_ctx, char **voltageUnit_val_ptr_ptr, size_t *voltageUnit_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != voltageUnit_val_ptr_ptr) && (NULL != *voltageUnit_val_ptr_ptr));
   netsnmp_assert( NULL != voltageUnit_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevVoltageTable:voltageUnit_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the voltageUnit data.
 * copy (* voltageUnit_val_ptr_ptr ) data and (* voltageUnit_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for voltageUnit data
     */
    if ((NULL == (* voltageUnit_val_ptr_ptr )) ||
        ((* voltageUnit_val_ptr_len_ptr ) <
         (rowreq_ctx->data.voltageUnit_len* sizeof(rowreq_ctx->data.voltageUnit[0])))) {
        /*
         * allocate space for voltageUnit data
         */
        (* voltageUnit_val_ptr_ptr ) = malloc(rowreq_ctx->data.voltageUnit_len* sizeof(rowreq_ctx->data.voltageUnit[0]));
        if(NULL == (* voltageUnit_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.voltageUnit)\n");
            return MFD_ERROR;
        }
    }
    (* voltageUnit_val_ptr_len_ptr ) = rowreq_ctx->data.voltageUnit_len* sizeof(rowreq_ctx->data.voltageUnit[0]);
    memcpy( (* voltageUnit_val_ptr_ptr ), rowreq_ctx->data.voltageUnit, rowreq_ctx->data.voltageUnit_len* sizeof(rowreq_ctx->data.voltageUnit[0]) );

    return MFD_SUCCESS;
} /* voltageUnit_get */



/** @} */
