/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "jbodDevLogTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement jbodDevLogTable get routines.
 * TODO:240:M: Implement jbodDevLogTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevLogTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevLogTable is subid 6 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.6, length: 10
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement jbodDevLogTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param logIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
jbodDevLogTable_indexes_set_tbl_idx(jbodDevLogTable_mib_index *tbl_idx, long logIndex_val)
{
    DEBUGMSGTL(("verbose:jbodDevLogTable:jbodDevLogTable_indexes_set_tbl_idx","called\n"));

    /* logIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/R/d/h */
    tbl_idx->logIndex = logIndex_val;
    

    return MFD_SUCCESS;
} /* jbodDevLogTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
jbodDevLogTable_indexes_set(jbodDevLogTable_rowreq_ctx *rowreq_ctx, long logIndex_val)
{
    DEBUGMSGTL(("verbose:jbodDevLogTable:jbodDevLogTable_indexes_set","called\n"));

    if(MFD_SUCCESS != jbodDevLogTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , logIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != jbodDevLogTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* jbodDevLogTable_indexes_set */


/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevLogEntry.logTime
 * logTime is subid 2 of jbodDevLogEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.6.1.2
 * Description:
Describe the event time
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the logTime data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param logTime_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param logTime_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by logTime.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*logTime_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update logTime_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
logTime_get( jbodDevLogTable_rowreq_ctx *rowreq_ctx, char **logTime_val_ptr_ptr, size_t *logTime_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != logTime_val_ptr_ptr) && (NULL != *logTime_val_ptr_ptr));
   netsnmp_assert( NULL != logTime_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevLogTable:logTime_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the logTime data.
 * copy (* logTime_val_ptr_ptr ) data and (* logTime_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for logTime data
     */
    if ((NULL == (* logTime_val_ptr_ptr )) ||
        ((* logTime_val_ptr_len_ptr ) <
         (rowreq_ctx->data.logTime_len* sizeof(rowreq_ctx->data.logTime[0])))) {
        /*
         * allocate space for logTime data
         */
        (* logTime_val_ptr_ptr ) = malloc(rowreq_ctx->data.logTime_len* sizeof(rowreq_ctx->data.logTime[0]));
        if(NULL == (* logTime_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.logTime)\n");
            return MFD_ERROR;
        }
    }
    (* logTime_val_ptr_len_ptr ) = rowreq_ctx->data.logTime_len* sizeof(rowreq_ctx->data.logTime[0]);
    memcpy( (* logTime_val_ptr_ptr ), rowreq_ctx->data.logTime, rowreq_ctx->data.logTime_len* sizeof(rowreq_ctx->data.logTime[0]) );

    return MFD_SUCCESS;
} /* logTime_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevLogEntry.logType
 * logType is subid 3 of jbodDevLogEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.6.1.3
 * Description:
Describe the log type - Info or Fail
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the logType data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param logType_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param logType_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by logType.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*logType_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update logType_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
logType_get( jbodDevLogTable_rowreq_ctx *rowreq_ctx, char **logType_val_ptr_ptr, size_t *logType_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != logType_val_ptr_ptr) && (NULL != *logType_val_ptr_ptr));
   netsnmp_assert( NULL != logType_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevLogTable:logType_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the logType data.
 * copy (* logType_val_ptr_ptr ) data and (* logType_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for logType data
     */
    if ((NULL == (* logType_val_ptr_ptr )) ||
        ((* logType_val_ptr_len_ptr ) <
         (rowreq_ctx->data.logType_len* sizeof(rowreq_ctx->data.logType[0])))) {
        /*
         * allocate space for logType data
         */
        (* logType_val_ptr_ptr ) = malloc(rowreq_ctx->data.logType_len* sizeof(rowreq_ctx->data.logType[0]));
        if(NULL == (* logType_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.logType)\n");
            return MFD_ERROR;
        }
    }
    (* logType_val_ptr_len_ptr ) = rowreq_ctx->data.logType_len* sizeof(rowreq_ctx->data.logType[0]);
    memcpy( (* logType_val_ptr_ptr ), rowreq_ctx->data.logType, rowreq_ctx->data.logType_len* sizeof(rowreq_ctx->data.logType[0]) );

    return MFD_SUCCESS;
} /* logType_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevLogEntry.logDescription
 * logDescription is subid 4 of jbodDevLogEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.6.1.4
 * Description:
Describe the log
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the logDescription data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param logDescription_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param logDescription_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by logDescription.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*logDescription_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update logDescription_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
logDescription_get( jbodDevLogTable_rowreq_ctx *rowreq_ctx, char **logDescription_val_ptr_ptr, size_t *logDescription_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != logDescription_val_ptr_ptr) && (NULL != *logDescription_val_ptr_ptr));
   netsnmp_assert( NULL != logDescription_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevLogTable:logDescription_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the logDescription data.
 * copy (* logDescription_val_ptr_ptr ) data and (* logDescription_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for logDescription data
     */
    if ((NULL == (* logDescription_val_ptr_ptr )) ||
        ((* logDescription_val_ptr_len_ptr ) <
         (rowreq_ctx->data.logDescription_len* sizeof(rowreq_ctx->data.logDescription[0])))) {
        /*
         * allocate space for logDescription data
         */
        (* logDescription_val_ptr_ptr ) = malloc(rowreq_ctx->data.logDescription_len* sizeof(rowreq_ctx->data.logDescription[0]));
        if(NULL == (* logDescription_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.logDescription)\n");
            return MFD_ERROR;
        }
    }
    (* logDescription_val_ptr_len_ptr ) = rowreq_ctx->data.logDescription_len* sizeof(rowreq_ctx->data.logDescription[0]);
    memcpy( (* logDescription_val_ptr_ptr ), rowreq_ctx->data.logDescription, rowreq_ctx->data.logDescription_len* sizeof(rowreq_ctx->data.logDescription[0]) );

    return MFD_SUCCESS;
} /* logDescription_get */



/** @} */
