/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 *
 * @file jbodDevFanTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef JBODDEVFANTABLE_DATA_GET_H
#define JBODDEVFANTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevFanTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevFanTable is subid 4 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.4, length: 10
*/
    /*
     * indexes
     */

    int fanDescription_get( jbodDevFanTable_rowreq_ctx *rowreq_ctx, char **fanDescription_val_ptr_ptr, size_t *fanDescription_val_ptr_len_ptr );
    int fanStatus_get( jbodDevFanTable_rowreq_ctx *rowreq_ctx, char **fanStatus_val_ptr_ptr, size_t *fanStatus_val_ptr_len_ptr );
    int fanValue_get( jbodDevFanTable_rowreq_ctx *rowreq_ctx, long * fanValue_val_ptr );
    int fanUnit_get( jbodDevFanTable_rowreq_ctx *rowreq_ctx, char **fanUnit_val_ptr_ptr, size_t *fanUnit_val_ptr_len_ptr );


int jbodDevFanTable_indexes_set_tbl_idx(jbodDevFanTable_mib_index *tbl_idx, long fanIndex_val);
int jbodDevFanTable_indexes_set(jbodDevFanTable_rowreq_ctx *rowreq_ctx, long fanIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* JBODDEVFANTABLE_DATA_GET_H */
/** @} */
