/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for jbodDevTemperatureTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "jbodDevTemperatureTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "jbodDevTemperatureTable_interface.h"

const oid jbodDevTemperatureTable_oid[] = { JBODDEVTEMPERATURETABLE_OID };
const int jbodDevTemperatureTable_oid_size = OID_LENGTH(jbodDevTemperatureTable_oid);

    jbodDevTemperatureTable_registration  jbodDevTemperatureTable_user_context;

void initialize_table_jbodDevTemperatureTable(void);
void shutdown_table_jbodDevTemperatureTable(void);


/**
 * Initializes the jbodDevTemperatureTable module
 */
void
init_jbodDevTemperatureTable(void)
{
    DEBUGMSGTL(("verbose:jbodDevTemperatureTable:init_jbodDevTemperatureTable","called\n"));

    /*
     * TODO:300:o: Perform jbodDevTemperatureTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("jbodDevTemperatureTable"))
        initialize_table_jbodDevTemperatureTable();

} /* init_jbodDevTemperatureTable */

/**
 * Shut-down the jbodDevTemperatureTable module (agent is exiting)
 */
void
shutdown_jbodDevTemperatureTable(void)
{
    if (should_init("jbodDevTemperatureTable"))
        shutdown_table_jbodDevTemperatureTable();

}

/**
 * Initialize the table jbodDevTemperatureTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_jbodDevTemperatureTable(void)
{
    jbodDevTemperatureTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:jbodDevTemperatureTable:initialize_table_jbodDevTemperatureTable","called\n"));

    /*
     * TODO:301:o: Perform jbodDevTemperatureTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize jbodDevTemperatureTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("jbodDevTemperatureTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _jbodDevTemperatureTable_initialize_interface(user_context, flags);
} /* initialize_table_jbodDevTemperatureTable */

/**
 * Shutdown the table jbodDevTemperatureTable 
 */
void
shutdown_table_jbodDevTemperatureTable(void)
{
    /*
     * call interface shutdown code
     */
    _jbodDevTemperatureTable_shutdown_interface(&jbodDevTemperatureTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
jbodDevTemperatureTable_rowreq_ctx_init(jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:jbodDevTemperatureTable:jbodDevTemperatureTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra jbodDevTemperatureTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* jbodDevTemperatureTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void jbodDevTemperatureTable_rowreq_ctx_cleanup(jbodDevTemperatureTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:jbodDevTemperatureTable:jbodDevTemperatureTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra jbodDevTemperatureTable rowreq cleanup.
     */
} /* jbodDevTemperatureTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
jbodDevTemperatureTable_pre_request(jbodDevTemperatureTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:jbodDevTemperatureTable:jbodDevTemperatureTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform jbodDevTemperatureTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* jbodDevTemperatureTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
jbodDevTemperatureTable_post_request(jbodDevTemperatureTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:jbodDevTemperatureTable:jbodDevTemperatureTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform jbodDevTemperatureTable post-request actions.
     */

    return MFD_SUCCESS;
} /* jbodDevTemperatureTable_post_request */


/** @{ */
