/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef JBODDEVVOLTAGETABLE_DATA_ACCESS_H
#define JBODDEVVOLTAGETABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevVoltageTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevVoltageTable is subid 3 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.3, length: 10
*/


    int jbodDevVoltageTable_init_data(jbodDevVoltageTable_registration * jbodDevVoltageTable_reg);


void jbodDevVoltageTable_container_init(netsnmp_container **container_ptr_ptr);
void jbodDevVoltageTable_container_shutdown(netsnmp_container *container_ptr);

int jbodDevVoltageTable_container_load(netsnmp_container *container);
void jbodDevVoltageTable_container_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int jbodDevVoltageTable_row_prep( jbodDevVoltageTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* JBODDEVVOLTAGETABLE_DATA_ACCESS_H */
