/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for jbodDevFanTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "jbodDevFanTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "jbodDevFanTable_interface.h"

const oid jbodDevFanTable_oid[] = { JBODDEVFANTABLE_OID };
const int jbodDevFanTable_oid_size = OID_LENGTH(jbodDevFanTable_oid);

    jbodDevFanTable_registration  jbodDevFanTable_user_context;

void initialize_table_jbodDevFanTable(void);
void shutdown_table_jbodDevFanTable(void);


/**
 * Initializes the jbodDevFanTable module
 */
void
init_jbodDevFanTable(void)
{
    DEBUGMSGTL(("verbose:jbodDevFanTable:init_jbodDevFanTable","called\n"));

    /*
     * TODO:300:o: Perform jbodDevFanTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("jbodDevFanTable"))
        initialize_table_jbodDevFanTable();

} /* init_jbodDevFanTable */

/**
 * Shut-down the jbodDevFanTable module (agent is exiting)
 */
void
shutdown_jbodDevFanTable(void)
{
    if (should_init("jbodDevFanTable"))
        shutdown_table_jbodDevFanTable();

}

/**
 * Initialize the table jbodDevFanTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_jbodDevFanTable(void)
{
    jbodDevFanTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:jbodDevFanTable:initialize_table_jbodDevFanTable","called\n"));

    /*
     * TODO:301:o: Perform jbodDevFanTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize jbodDevFanTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("jbodDevFanTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _jbodDevFanTable_initialize_interface(user_context, flags);
} /* initialize_table_jbodDevFanTable */

/**
 * Shutdown the table jbodDevFanTable 
 */
void
shutdown_table_jbodDevFanTable(void)
{
    /*
     * call interface shutdown code
     */
    _jbodDevFanTable_shutdown_interface(&jbodDevFanTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
jbodDevFanTable_rowreq_ctx_init(jbodDevFanTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:jbodDevFanTable:jbodDevFanTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra jbodDevFanTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* jbodDevFanTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void jbodDevFanTable_rowreq_ctx_cleanup(jbodDevFanTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:jbodDevFanTable:jbodDevFanTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra jbodDevFanTable rowreq cleanup.
     */
} /* jbodDevFanTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
jbodDevFanTable_pre_request(jbodDevFanTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:jbodDevFanTable:jbodDevFanTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform jbodDevFanTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* jbodDevFanTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
jbodDevFanTable_post_request(jbodDevFanTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:jbodDevFanTable:jbodDevFanTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform jbodDevFanTable post-request actions.
     */

    return MFD_SUCCESS;
} /* jbodDevFanTable_post_request */


/** @{ */
