/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "jbodDevDiskTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement jbodDevDiskTable get routines.
 * TODO:240:M: Implement jbodDevDiskTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table jbodDevDiskTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * INWIN-JBOD-MIB::jbodDevDiskTable is subid 5 of product.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.47464.1.2.5, length: 10
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement jbodDevDiskTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param diskIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
jbodDevDiskTable_indexes_set_tbl_idx(jbodDevDiskTable_mib_index *tbl_idx, long diskIndex_val)
{
    DEBUGMSGTL(("verbose:jbodDevDiskTable:jbodDevDiskTable_indexes_set_tbl_idx","called\n"));

    /* diskIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/R/d/h */
    tbl_idx->diskIndex = diskIndex_val;
    

    return MFD_SUCCESS;
} /* jbodDevDiskTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
jbodDevDiskTable_indexes_set(jbodDevDiskTable_rowreq_ctx *rowreq_ctx, long diskIndex_val)
{
    DEBUGMSGTL(("verbose:jbodDevDiskTable:jbodDevDiskTable_indexes_set","called\n"));

    if(MFD_SUCCESS != jbodDevDiskTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , diskIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != jbodDevDiskTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* jbodDevDiskTable_indexes_set */


/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevDiskEntry.phyId
 * phyId is subid 2 of jbodDevDiskEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.5.1.2
 * Description:
Expander's PHY ID
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 2147483647;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the phyId data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param phyId_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
phyId_get( jbodDevDiskTable_rowreq_ctx *rowreq_ctx, long * phyId_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != phyId_val_ptr );


    DEBUGMSGTL(("verbose:jbodDevDiskTable:phyId_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the phyId data.
 * copy (* phyId_val_ptr ) from rowreq_ctx->data
 */
    (* phyId_val_ptr ) = rowreq_ctx->data.phyId;

    return MFD_SUCCESS;
} /* phyId_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevDiskEntry.nlRate
 * nlRate is subid 3 of jbodDevDiskEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.5.1.3
 * Description:
Disk support rate
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 2147483647;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the nlRate data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param nlRate_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
nlRate_get( jbodDevDiskTable_rowreq_ctx *rowreq_ctx, long * nlRate_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != nlRate_val_ptr );


    DEBUGMSGTL(("verbose:jbodDevDiskTable:nlRate_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the nlRate data.
 * copy (* nlRate_val_ptr ) from rowreq_ctx->data
 */
    (* nlRate_val_ptr ) = rowreq_ctx->data.nlRate;

    return MFD_SUCCESS;
} /* nlRate_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevDiskEntry.sasAddress
 * sasAddress is subid 4 of jbodDevDiskEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.5.1.4
 * Description:
Describe the disk SAS address
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  8;
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 8)
 */
/**
 * Extract the current value of the sasAddress data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param sasAddress_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param sasAddress_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by sasAddress.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*sasAddress_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update sasAddress_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
sasAddress_get( jbodDevDiskTable_rowreq_ctx *rowreq_ctx, char **sasAddress_val_ptr_ptr, size_t *sasAddress_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != sasAddress_val_ptr_ptr) && (NULL != *sasAddress_val_ptr_ptr));
   netsnmp_assert( NULL != sasAddress_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevDiskTable:sasAddress_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the sasAddress data.
 * copy (* sasAddress_val_ptr_ptr ) data and (* sasAddress_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for sasAddress data
     */
    if ((NULL == (* sasAddress_val_ptr_ptr )) ||
        ((* sasAddress_val_ptr_len_ptr ) <
         (rowreq_ctx->data.sasAddress_len* sizeof(rowreq_ctx->data.sasAddress[0])))) {
        /*
         * allocate space for sasAddress data
         */
        (* sasAddress_val_ptr_ptr ) = malloc(rowreq_ctx->data.sasAddress_len* sizeof(rowreq_ctx->data.sasAddress[0]));
        if(NULL == (* sasAddress_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.sasAddress)\n");
            return MFD_ERROR;
        }
    }
    (* sasAddress_val_ptr_len_ptr ) = rowreq_ctx->data.sasAddress_len* sizeof(rowreq_ctx->data.sasAddress[0]);
    memcpy( (* sasAddress_val_ptr_ptr ), rowreq_ctx->data.sasAddress, rowreq_ctx->data.sasAddress_len* sizeof(rowreq_ctx->data.sasAddress[0]) );

    return MFD_SUCCESS;
} /* sasAddress_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevDiskEntry.diskType
 * diskType is subid 5 of jbodDevDiskEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.5.1.5
 * Description:
Describe the disk type
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the diskType data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param diskType_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param diskType_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by diskType.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*diskType_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update diskType_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
diskType_get( jbodDevDiskTable_rowreq_ctx *rowreq_ctx, char **diskType_val_ptr_ptr, size_t *diskType_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != diskType_val_ptr_ptr) && (NULL != *diskType_val_ptr_ptr));
   netsnmp_assert( NULL != diskType_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevDiskTable:diskType_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the diskType data.
 * copy (* diskType_val_ptr_ptr ) data and (* diskType_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for diskType data
     */
    if ((NULL == (* diskType_val_ptr_ptr )) ||
        ((* diskType_val_ptr_len_ptr ) <
         (rowreq_ctx->data.diskType_len* sizeof(rowreq_ctx->data.diskType[0])))) {
        /*
         * allocate space for diskType data
         */
        (* diskType_val_ptr_ptr ) = malloc(rowreq_ctx->data.diskType_len* sizeof(rowreq_ctx->data.diskType[0]));
        if(NULL == (* diskType_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.diskType)\n");
            return MFD_ERROR;
        }
    }
    (* diskType_val_ptr_len_ptr ) = rowreq_ctx->data.diskType_len* sizeof(rowreq_ctx->data.diskType[0]);
    memcpy( (* diskType_val_ptr_ptr ), rowreq_ctx->data.diskType, rowreq_ctx->data.diskType_len* sizeof(rowreq_ctx->data.diskType[0]) );

    return MFD_SUCCESS;
} /* diskType_get */

/*---------------------------------------------------------------------
 * INWIN-JBOD-MIB::jbodDevDiskEntry.status
 * status is subid 6 of jbodDevDiskEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.47464.1.2.5.1.6
 * Description:
Describe the PHY status
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 128;
 *
 * Its syntax is SnmpAdminString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 128)
 */
/**
 * Extract the current value of the status data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param status_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param status_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by status.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*status_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update status_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
status_get( jbodDevDiskTable_rowreq_ctx *rowreq_ctx, char **status_val_ptr_ptr, size_t *status_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != status_val_ptr_ptr) && (NULL != *status_val_ptr_ptr));
   netsnmp_assert( NULL != status_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:jbodDevDiskTable:status_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the status data.
 * copy (* status_val_ptr_ptr ) data and (* status_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for status data
     */
    if ((NULL == (* status_val_ptr_ptr )) ||
        ((* status_val_ptr_len_ptr ) <
         (rowreq_ctx->data.status_len* sizeof(rowreq_ctx->data.status[0])))) {
        /*
         * allocate space for status data
         */
        (* status_val_ptr_ptr ) = malloc(rowreq_ctx->data.status_len* sizeof(rowreq_ctx->data.status[0]));
        if(NULL == (* status_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.status)\n");
            return MFD_ERROR;
        }
    }
    (* status_val_ptr_len_ptr ) = rowreq_ctx->data.status_len* sizeof(rowreq_ctx->data.status[0]);
    memcpy( (* status_val_ptr_ptr ), rowreq_ctx->data.status, rowreq_ctx->data.status_len* sizeof(rowreq_ctx->data.status[0]) );

    return MFD_SUCCESS;
} /* status_get */



/** @} */
