/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef JBODDEVFANTABLE_OIDS_H
#define JBODDEVFANTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table jbodDevFanTable */
#define JBODDEVFANTABLE_OID              1,3,6,1,4,1,47464,1,2,4


#define COLUMN_FANINDEX         1
    
#define COLUMN_FANDESCRIPTION         2
    
#define COLUMN_FANSTATUS         3
    
#define COLUMN_FANVALUE         4
    
#define COLUMN_FANUNIT         5
    

#define JBODDEVFANTABLE_MIN_COL   COLUMN_FANDESCRIPTION
#define JBODDEVFANTABLE_MAX_COL   COLUMN_FANUNIT
    


#ifdef __cplusplus
}
#endif

#endif /* JBODDEVFANTABLE_OIDS_H */
