/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef JBODDEVVOLTAGETABLE_OIDS_H
#define JBODDEVVOLTAGETABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table jbodDevVoltageTable */
#define JBODDEVVOLTAGETABLE_OID              1,3,6,1,4,1,47464,1,2,3


#define COLUMN_VOLTAGEINDEX         1
    
#define COLUMN_VOLTAGEDESCRIPTION         2
    
#define COLUMN_VOLTAGESTATUS         3
    
#define COLUMN_VOLTAGEVALUE         4
    
#define COLUMN_VOLTAGEUNIT         5
    

#define JBODDEVVOLTAGETABLE_MIN_COL   COLUMN_VOLTAGEDESCRIPTION
#define JBODDEVVOLTAGETABLE_MAX_COL   COLUMN_VOLTAGEUNIT
    


#ifdef __cplusplus
}
#endif

#endif /* JBODDEVVOLTAGETABLE_OIDS_H */
