/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef JBODDEVLOGTABLE_OIDS_H
#define JBODDEVLOGTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table jbodDevLogTable */
#define JBODDEVLOGTABLE_OID              1,3,6,1,4,1,47464,1,2,6


#define COLUMN_LOGINDEX         1
    
#define COLUMN_LOGTIME         2
    
#define COLUMN_LOGTYPE         3
    
#define COLUMN_LOGDESCRIPTION         4
    

#define JBODDEVLOGTABLE_MIN_COL   COLUMN_LOGTIME
#define JBODDEVLOGTABLE_MAX_COL   COLUMN_LOGDESCRIPTION
    


#ifdef __cplusplus
}
#endif

#endif /* JBODDEVLOGTABLE_OIDS_H */
