/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for jbodDevLogTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "jbodDevLogTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "jbodDevLogTable_interface.h"

const oid jbodDevLogTable_oid[] = { JBODDEVLOGTABLE_OID };
const int jbodDevLogTable_oid_size = OID_LENGTH(jbodDevLogTable_oid);

    jbodDevLogTable_registration  jbodDevLogTable_user_context;

void initialize_table_jbodDevLogTable(void);
void shutdown_table_jbodDevLogTable(void);


/**
 * Initializes the jbodDevLogTable module
 */
void
init_jbodDevLogTable(void)
{
    DEBUGMSGTL(("verbose:jbodDevLogTable:init_jbodDevLogTable","called\n"));

    /*
     * TODO:300:o: Perform jbodDevLogTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("jbodDevLogTable"))
        initialize_table_jbodDevLogTable();

} /* init_jbodDevLogTable */

/**
 * Shut-down the jbodDevLogTable module (agent is exiting)
 */
void
shutdown_jbodDevLogTable(void)
{
    if (should_init("jbodDevLogTable"))
        shutdown_table_jbodDevLogTable();

}

/**
 * Initialize the table jbodDevLogTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_jbodDevLogTable(void)
{
    jbodDevLogTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:jbodDevLogTable:initialize_table_jbodDevLogTable","called\n"));

    /*
     * TODO:301:o: Perform jbodDevLogTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize jbodDevLogTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("jbodDevLogTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _jbodDevLogTable_initialize_interface(user_context, flags);
} /* initialize_table_jbodDevLogTable */

/**
 * Shutdown the table jbodDevLogTable 
 */
void
shutdown_table_jbodDevLogTable(void)
{
    /*
     * call interface shutdown code
     */
    _jbodDevLogTable_shutdown_interface(&jbodDevLogTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
jbodDevLogTable_rowreq_ctx_init(jbodDevLogTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:jbodDevLogTable:jbodDevLogTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra jbodDevLogTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* jbodDevLogTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void jbodDevLogTable_rowreq_ctx_cleanup(jbodDevLogTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:jbodDevLogTable:jbodDevLogTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra jbodDevLogTable rowreq cleanup.
     */
} /* jbodDevLogTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
jbodDevLogTable_pre_request(jbodDevLogTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:jbodDevLogTable:jbodDevLogTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform jbodDevLogTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* jbodDevLogTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
jbodDevLogTable_post_request(jbodDevLogTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:jbodDevLogTable:jbodDevLogTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform jbodDevLogTable post-request actions.
     */

    return MFD_SUCCESS;
} /* jbodDevLogTable_post_request */


/** @{ */
