/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.create-dataset.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "platform.h"

/** Initialize the jbodDevTemperatureTable table by defining its contents and how it's structured */
void
initialize_table_jbodDevTemperatureTable(void)
{
    const oid jbodDevTemperatureTable_oid[] = {1,3,6,1,4,1,47464,1,2,2};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("jbodDevTemperatureTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_jbodDevTemperatureTable",
                "adding indexes to table jbodDevTemperatureTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: temperatureIndex */
                           0);

    DEBUGMSGTL(("initialize_table_jbodDevTemperatureTable",
                "adding column types to table jbodDevTemperatureTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_TEMPERATUREINDEX, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_TEMPERATUREDESCRIPTION, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_TEMPERATURESTATUS, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_TEMPERATUREVALUE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_TEMPERATUREUNIT, ASN_OCTET_STR, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change jbodDevTemperatureTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("jbodDevTemperatureTable", jbodDevTemperatureTable_handler,
                                                        jbodDevTemperatureTable_oid,
                                                        OID_LENGTH(jbodDevTemperatureTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}
/** Initialize the jbodDevVoltageTable table by defining its contents and how it's structured */
void
initialize_table_jbodDevVoltageTable(void)
{
    const oid jbodDevVoltageTable_oid[] = {1,3,6,1,4,1,47464,1,2,3};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("jbodDevVoltageTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_jbodDevVoltageTable",
                "adding indexes to table jbodDevVoltageTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: voltageIndex */
                           0);

    DEBUGMSGTL(("initialize_table_jbodDevVoltageTable",
                "adding column types to table jbodDevVoltageTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_VOLTAGEINDEX, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_VOLTAGEDESCRIPTION, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_VOLTAGESTATUS, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_VOLTAGEVALUE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_VOLTAGEUNIT, ASN_OCTET_STR, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change jbodDevVoltageTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("jbodDevVoltageTable", jbodDevVoltageTable_handler,
                                                        jbodDevVoltageTable_oid,
                                                        OID_LENGTH(jbodDevVoltageTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}
/** Initialize the jbodDevFanTable table by defining its contents and how it's structured */
void
initialize_table_jbodDevFanTable(void)
{
    const oid jbodDevFanTable_oid[] = {1,3,6,1,4,1,47464,1,2,4};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("jbodDevFanTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_jbodDevFanTable",
                "adding indexes to table jbodDevFanTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: fanIndex */
                           0);

    DEBUGMSGTL(("initialize_table_jbodDevFanTable",
                "adding column types to table jbodDevFanTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_FANINDEX, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_FANDESCRIPTION, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_FANSTATUS, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_FANVALUE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_FANUNIT, ASN_OCTET_STR, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change jbodDevFanTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("jbodDevFanTable", jbodDevFanTable_handler,
                                                        jbodDevFanTable_oid,
                                                        OID_LENGTH(jbodDevFanTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}
/** Initialize the jbodDevDiskTable table by defining its contents and how it's structured */
void
initialize_table_jbodDevDiskTable(void)
{
    const oid jbodDevDiskTable_oid[] = {1,3,6,1,4,1,47464,1,2,5};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("jbodDevDiskTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_jbodDevDiskTable",
                "adding indexes to table jbodDevDiskTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: diskIndex */
                           0);

    DEBUGMSGTL(("initialize_table_jbodDevDiskTable",
                "adding column types to table jbodDevDiskTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_DISKINDEX, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_PHYID, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_NLRATE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_SASADDRESS, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_DISKTYPE, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_STATUS, ASN_OCTET_STR, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change jbodDevDiskTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("jbodDevDiskTable", jbodDevDiskTable_handler,
                                                        jbodDevDiskTable_oid,
                                                        OID_LENGTH(jbodDevDiskTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);

    netsnmp_table_row *row = netsnmp_create_table_data_row();
    int index = 1;
    int phyid = 12;
    int nlrate = 12;
    netsnmp_table_row_add_index(row, ASN_INTEGER, &index, 4);
    netsnmp_set_row_column(row, COLUMN_PHYID, ASN_INTEGER, &phyid, 4);
    netsnmp_set_row_column(row, COLUMN_NLRATE, ASN_INTEGER, &nlrate, 4);
    netsnmp_set_row_column(row, COLUMN_SASADDRESS, ASN_OCTET_STR, "5000C500_83D8F3F9", 17);
    netsnmp_set_row_column(row, COLUMN_DISKTYPE, ASN_OCTET_STR, "SAS", 3);
    netsnmp_set_row_column(row, COLUMN_STATUS, ASN_OCTET_STR, "OK", 2);
    netsnmp_table_dataset_add_row(table_set, row);
    /*
     * Finally, this actually allows the "add_row" token it the
     * * snmpd.conf file to add rows to this table.
     * * Example snmpd.conf line:
     * *   add_row netSnmpIETFWGTable eos "Glenn Waters" "Dale Francisco"
     */
    netsnmp_register_auto_data_table(table_set, NULL);
}

/** Initialize the jbodDevLogTable table by defining its contents and how it's structured */
void
initialize_table_jbodDevLogTable(void)
{
    const oid jbodDevLogTable_oid[] = {1,3,6,1,4,1,47464,1,2,6};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("jbodDevLogTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_jbodDevLogTable",
                "adding indexes to table jbodDevLogTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: logIndex */
                           0);

    DEBUGMSGTL(("initialize_table_jbodDevLogTable",
                "adding column types to table jbodDevLogTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_LOGINDEX, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_LOGTIME, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_LOGTYPE, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_LOGDESCRIPTION, ASN_OCTET_STR, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change jbodDevLogTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("jbodDevLogTable", jbodDevLogTable_handler,
                                                        jbodDevLogTable_oid,
                                                        OID_LENGTH(jbodDevLogTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}

/** Initializes the platform module */
void
init_platform(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_jbodDevTemperatureTable();
    initialize_table_jbodDevVoltageTable();
    initialize_table_jbodDevFanTable();
    initialize_table_jbodDevDiskTable();
    initialize_table_jbodDevLogTable();
}

/** handles requests for the jbodDevTemperatureTable table, if anything else needs to be done */
int
jbodDevTemperatureTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}

/** handles requests for the jbodDevVoltageTable table, if anything else needs to be done */
int
jbodDevVoltageTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}

/** handles requests for the jbodDevFanTable table, if anything else needs to be done */
int
jbodDevFanTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}

/** handles requests for the jbodDevDiskTable table, if anything else needs to be done */
int
jbodDevDiskTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}

/** handles requests for the jbodDevLogTable table, if anything else needs to be done */
int
jbodDevLogTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
