/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.create-dataset.conf
 */
#ifndef PLATFORM_H
#define PLATFORM_H

/* function declarations */
void init_platform(void);
void initialize_table_jbodDevTemperatureTable(void);
Netsnmp_Node_Handler jbodDevTemperatureTable_handler;
void initialize_table_jbodDevVoltageTable(void);
Netsnmp_Node_Handler jbodDevVoltageTable_handler;
void initialize_table_jbodDevFanTable(void);
Netsnmp_Node_Handler jbodDevFanTable_handler;
void initialize_table_jbodDevDiskTable(void);
Netsnmp_Node_Handler jbodDevDiskTable_handler;
void initialize_table_jbodDevLogTable(void);
Netsnmp_Node_Handler jbodDevLogTable_handler;

/* column number definitions for table jbodDevTemperatureTable */
       #define COLUMN_TEMPERATUREINDEX		1
       #define COLUMN_TEMPERATUREDESCRIPTION		2
       #define COLUMN_TEMPERATURESTATUS		3
       #define COLUMN_TEMPERATUREVALUE		4
       #define COLUMN_TEMPERATUREUNIT		5

/* column number definitions for table jbodDevVoltageTable */
       #define COLUMN_VOLTAGEINDEX		1
       #define COLUMN_VOLTAGEDESCRIPTION		2
       #define COLUMN_VOLTAGESTATUS		3
       #define COLUMN_VOLTAGEVALUE		4
       #define COLUMN_VOLTAGEUNIT		5

/* column number definitions for table jbodDevFanTable */
       #define COLUMN_FANINDEX		1
       #define COLUMN_FANDESCRIPTION		2
       #define COLUMN_FANSTATUS		3
       #define COLUMN_FANVALUE		4
       #define COLUMN_FANUNIT		5

/* column number definitions for table jbodDevDiskTable */
       #define COLUMN_DISKINDEX		1
       #define COLUMN_PHYID		2
       #define COLUMN_NLRATE		3
       #define COLUMN_SASADDRESS		4
       #define COLUMN_DISKTYPE		5
       #define COLUMN_STATUS		6

/* column number definitions for table jbodDevLogTable */
       #define COLUMN_LOGINDEX		1
       #define COLUMN_LOGTIME		2
       #define COLUMN_LOGTYPE		3
       #define COLUMN_LOGDESCRIPTION		4
#endif /* PLATFORM_H */
